name: Upstream Sync

permissions:
  contents: write
  actions: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * 0" # 每周日UTC时间0点（北京时间周一8点）
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits (手动模式)
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 使用 ${{ secrets.GITHUB_TOKEN }} 确保 Git 命令有权限
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote and fetch
        run: |
          # 1. 添加上游仓库为新的 remote
          git remote add upstream https://github.com/willow-god/Friend-Circle-Lite.git
          # 2. 从上游仓库拉取最新更改
          git fetch upstream

      - name: Sync and handle conflicts
        run: |
          # 3. 切换到主分支
          git checkout main
          # 4. 从上游分支拉取更改，但先不提交
          git pull upstream main --no-commit --no-rebase --allow-unrelated-histories
          # 5. 恢复 conf.yaml 到本地版本
          git checkout HEAD -- conf.yaml
          # 6. 提交合并后的更改
          git commit -m "Auto-sync from upstream/main"
          # 7. 强制推送到你自己的仓库
          git push -f origin main
