name: Upstream Sync

# 全局权限配置，保持不变
permissions:
  contents: write
  actions: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * 0" # 每周日UTC时间0点（北京时间周一8点）
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits (手动模式)
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 关键修改：使用你新创建的 PAT
          token: ${{ secrets.GITHUB_PAT_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Sync upstream
        run: |
          # 1. 设置上游远程仓库
          git remote add upstream https://github.com/willow-god/Friend-Circle-Lite.git
          # 2. 从上游拉取并进行 rebase
          git fetch upstream
          git checkout main
          git rebase upstream/main
          # 3. 排除 conf.yaml
          git checkout HEAD -- conf.yaml
          # 4. 提交和推送
          git commit -a -m "Auto-sync from upstream/main"
          git push -f origin main
