name: Upstream Sync

# 全局权限配置，但不是解决问题的关键
permissions:
  contents: write
  actions: write
  pull-requests: write

on:
  schedule:
    - cron: "0 0 * * 0" # 每周日UTC时间0点（北京时间周一8点）
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits (手动模式)
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    permissions:
      contents: write
      actions: write
      pull-requests: write
      workflows: write # 明确声明权限

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/willow-god/Friend-Circle-Lite.git
          git fetch upstream

      - name: Sync and handle conflicts
        run: |
          git checkout main
          git pull upstream main --no-commit --no-rebase --allow-unrelated-histories
          git checkout HEAD -- conf.yaml
          git commit -m "Auto-sync from upstream/main"
          git push -f origin main
